/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/
#include <stdio.h>
int main(){
    long last_term, second_last_term, sum;
    last_term = 2, second_last_term = 1;
    while(last_term < 4000000){
        if (last_term % 2 == 0) {
            sum += last_term;
        }
        long temp;
        temp = last_term;
        last_term += second_last_term;
        second_last_term = temp;
    }
    printf("%ld\n", sum);
}
